name: CI-SBOM

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  spdx_creation:
    name: Create Software Bill of Materials
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          sudo apt update && sudo apt install cargo
          cargo install cargo-bom
      - name: Run SPDX Creation for flake-ctl
        run: |
          cd flake-ctl
          cargo bom
      - name: Run SPDX Creation for podman-pilot
        run: |
          cd podman-pilot
          cargo bom
